import { useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
//import { Inter } from "@next/font/google";
import Link from "next/link";
import Page from "@/components/layout/Page";
import { getFontsArray } from "@/utils/fonts";
import { useSelector, useDispatch } from "react-redux";
import { updateFont, selectFonts } from "@/store/fontsSlice";

const style = {
  height: "100vh",
  width: "100vw",
  backgroundColor: "#FFFFE0",
};

let options = getFontsArray();

//const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const dispatch = useDispatch();
  const themeFonts = useSelector(selectFonts);

  useEffect(() => {
    console.log("themeFonts:", themeFonts);
  }, []);

  const test = (val) => {
    val.key = "body";
    dispatch(updateFont(val));
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Link type="button" href="/playground">
          To Playground
        </Link>
      </main>
    </>
  );
}
